// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

/**
 * Props for OnEventHandlerFunction
 */
export interface OnEventHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/account-provider/on-event-handler.
 */
export class OnEventHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: OnEventHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/account-provider/on-event-handler.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/account-provider/on-event-handler.lambda')),
    });
  }
}